language: node_js

node_js:
  - "8.9"

sudo: required

cache:
  directories:
    - node_modules

addons:
  chrome: stable

before_install:
  # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set spin false"

before_script:
  - "npm install"
  - "npm install -g reg-suit"
script:
  - npm test -- wdio.conf.local.js
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*" # This line is necessary to disable --single-branch option to fetch all remote branches on TravisCI.
  - git fetch origin # Ditto
  - git checkout $TRAVIS_BRANCH || git checkout -b $TRAVIS_BRANCH
  - reg-suit run
